### ISSUE TITLE
Can't install aloe on Mac OS

### ISSUE THREAD

**Issue by Ryskulov** [koterpillar/aloe#130]
If I try `pip install aloe` or aloe 0.1.12
I have this error:

```
Collecting aloe
  Using cached aloe-0.1.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zb/6hp0hmgs4kdcyqp4s24n42280000gn/T/pip-build-m0nngnci/aloe/setup.py", line 19, in <module>
        long_description=readme.read(),
      File "/Users/randomir/Projects/heartbeat-src/venv/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2369: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/zb/6hp0hmgs4kdcyqp4s24n42280000gn/T/pip-build-m0nngnci/aloe/
```

Mac OS Sierra
python versions: 3.4.3 ; 3.5.2 ; 3.6.1

**Comment by koterpillar** [comment]
Do you have an outdated `pip`?

```shell
$ python3 -m venv env
$ . env/bin/activate
(env) $ pip --version
pip 9.0.1 from .../env/lib/python3.6/site-packages (python 3.6)
(env) $ pip install aloe
Collecting aloe
  Downloading aloe-0.1.12.tar.gz (92kB)
    100% |████████████████████████████████| 102kB 1.3MB/s
Collecting blessings (from aloe)
  Downloading blessings-1.6.tar.gz
Collecting future>=0.14.0 (from aloe)
  Downloading future-0.16.0.tar.gz (824kB)
    100% |████████████████████████████████| 829kB 1.3MB/s
Collecting gherkin-official<5,>=4 (from aloe)
  Downloading gherkin-official-4.1.3.tar.gz
Collecting nose (from aloe)
  Downloading nose-1.3.7-py3-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 3.9MB/s
Collecting repoze.lru (from aloe)
  Downloading repoze.lru-0.6.tar.gz
Installing collected packages: blessings, future, gherkin-official, nose, repoze.lru, aloe
  Running setup.py install for blessings ... done
  Running setup.py install for future ... done
  Running setup.py install for gherkin-official ... done
  Running setup.py install for repoze.lru ... done
  Running setup.py install for aloe ... done
Successfully installed aloe-0.1.12 blessings-1.6 future-0.16.0 gherkin-official-4.1.3 nose-1.3.7 repoze.lru-0.6
(env) $ uname -a
Darwin ... 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
```

**Comment by Ryskulov** [comment]
Yes I have new version of pip 9.0.1

```shell
➜  ~ pip --version
pip 9.0.1 from /Users/randomir/.pyenv/versions/3.5.2/lib/python3.5/site-packages (python 3.5)
➜  ~ python --version
Python 3.5.2
➜  ~ pip install aloe
Collecting aloe
  Using cached aloe-0.1.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zb/6hp0hmgs4kdcyqp4s24n42280000gn/T/pip-build-f53lo1nq/aloe/setup.py", line 19, in <module>
        long_description=readme.read(),
      File "/Users/randomir/.pyenv/versions/3.5.2/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2369: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/zb/6hp0hmgs4kdcyqp4s24n42280000gn/T/pip-build-f53lo1nq/aloe/
➜  ~
```

**Comment by koterpillar** [comment]
How did you install this pip and python? I have just tried with pyenv and still don't get errors. Also, please show the output of `locale`.

**Comment by Ryskulov** [comment]
I installed with brew and pyenv. maybe I have some system problem ? But really i don't know why this error only with aloe.

I used old version 0.0.35 worked good, but when I try install new version I had this error

**Comment by koterpillar** [comment]
Can you please wipe or move away `~/.pyenv` and start from scratch, noting all the commands? Also, I still want to see the `locale` output.
