### ISSUE TITLE
Assertion Error in the aloe library

### ISSUE THREAD

**Issue by mkmad** [koterpillar/aloe#156]
When I use aloe to run my behaviour tests I get this error which seems to originate from within the library:

```
FAIL: Failure: AssertionError ()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "~/home/bootstrap/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "~/home/bootstrap/lib/python3.7/site-packages/nose/plugins/manager.py", line 154, in generate
    for r in result:
  File "~/home/bootstrap/lib/python3.7/site-packages/aloe/plugin.py", line 201, in loadTestsFromFile
    test = self.test_class.from_file(file_)
  File "~/home/bootstrap/lib/python3.7/site-packages/aloe/testclass.py", line 171, in from_file
    background = cls.make_background(feature.background)
  File "~/home/bootstrap/lib/python3.7/site-packages/aloe/testclass.py", line 210, in make_background
    is_background=True)
  File "~/home/bootstrap/lib/python3.7/site-packages/aloe/testclass.py", line 311, in make_steps
    assert steps
AssertionError: 
>>  assert ()
```

This error is not related to any of my behaviour tests! Any help on this is really appreciated. 

thanks!

**Comment by koterpillar** [comment]
If you are still having this issue, do you mind showing your feature file?
