### ISSUE TITLE
step.given() does not work

### ISSUE THREAD

**Issue by danni** [koterpillar/aloe#23]
```
Traceback (most recent call last):
  File "/app/python_env/local/lib/python2.7/site-packages/aloe/registry.py", line 178, in wrapped
    return function(*args, **kwargs)
  File "ixlogin/features/profile_management/change_password.feature", line 70, in Password too simple
    When I log in with username "alice_l" and password "secret"
  File "/app/python_env/local/lib/python2.7/site-packages/aloe/registry.py", line 178, in wrapped
    return function(*args, **kwargs)
  File "/app/ixlogin/features/steps/browser.py", line 132, in log_in
    authenticate(step, username, password)
  File "/app/ixlogin/features/steps/browser.py", line 102, in authenticate
    self.given('I fill in "Username" with "%s"' % username)
AttributeError: 'function' object has no attribute 'given'
```

The step is defined as:

```
@step(r'I authenticate with (?:username|email) "([^"]*)" ' +                     
      'and password "([^"]*)"')                                                  
def authenticate(self, username, password):                                      
    """                                                                          
    Authenticate in an already-open login form                                   
    """                                                                          

    # Login button and username input have different text in some themes
    username_field = find_field(world.browser, 'text', "Username")               
    if username_field:                                                           
        self.given('I fill in "Username" with "%s"' % username)                  
    else:                                                                        
        self.given('I fill in "Email" with "%s"' % username)                     

    self.given('I authenticate with password "%s"' % password) 
```

`self` appears to be the wrong thing:

```
-> self.given('I fill in "Username" with "%s"' % username)
(Pdb) p self
<bound method StepDict.step of {<_sre.SRE_Pattern object at 0x7f382576eab0>: <function check_u...
```

**Comment by koterpillar** [comment]
Where's the definition for `log_in`? It is the one passing `step` to `authenticate`, not Aloe.

**Comment by danni** [comment]
Urgh. Error 11. Sorry!
