### ISSUE TITLE
Not found steps with unicode characters raise UnicodeEncodeError

### ISSUE THREAD

**Issue by michelts** [koterpillar/aloe#50]
Hi!

If a not found step has unicode characters, I fall in a UnicodeDecodeError. I'm using python2.7:

```
$ aloe features 
E
======================================================================
Traceback (most recent call last):
  File ".../bin/aloe", line 9, in <module>
    load_entry_point('aloe==0.0.25', 'console_scripts', 'aloe')()
  File ".../local/lib/python2.7/site-packages/aloe/__init__.py", line 36, in main
    Runner(argv)
  File ".../local/lib/python2.7/site-packages/aloe/runner.py", line 48, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/usr/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/usr/lib/python2.7/dist-packages/nose/core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "/usr/lib/python2.7/dist-packages/nose/core.py", line 66, in run
    result.printErrors()
  File "/usr/lib/python2.7/dist-packages/nose/result.py", line 103, in printErrors
    _TextTestResult.printErrors(self)
  File "/usr/lib/python2.7/unittest/runner.py", line 108, in printErrors
    self.printErrorList('ERROR', self.errors)
  File "/usr/lib/python2.7/unittest/runner.py", line 114, in printErrorList
    self.stream.writeln("%s: %s" % (flavour,self.getDescription(test)))
  File "/usr/lib/python2.7/dist-packages/nose/result.py", line 82, in getDescription
    return test.shortDescription() or str(test)
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 51, in __str__
    return str(self.test)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfa' in position 63: ordinal not in range(128)
```

I try to fix it changing the method aloe/exceptions.py:NoDefinitionFound.**init**.py, making the whole argument of the super call utf-8 encoded:

```
- super().__init__('The step r"%s" is not defined' % self.step.sentence)
+ super().__init__(('The step r"%s" is not defined' % self.step.sentence).encode('utf-8'))
```

I make a fork to write some tests. I plan to finish it tomorrow.

**Comment by koterpillar** [comment]
I wrote a test that checks this (#51), but I'm not sure explicitly mentioning `utf-8` is a good idea - _technically_ the system default encoding should be used.

**Comment by koterpillar** [comment]
From what I can see, this is a Nose problem, will probably raise a bug with them.

**Comment by koterpillar** [comment]
Okay, it's even worse:

```
Python 2.7.10 (default, Sep  7 2015, 13:51:49) 
[GCC 5.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> str(Exception(u"哈哈"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

Given this, I'm going to follow your suggestion.

**Comment by koterpillar** [comment]
@michelts can you please verify the fix in #51?

**Comment by michelts** [comment]
@koterpillar thanks for the quick reply. It worked like a charm!

Best regards.

**Comment by koterpillar** [comment]
Released to PyPI.
