### ISSUE TITLE
Aloe import breaking selenium phantomjs webdriver

### ISSUE THREAD

**Issue by hylyh** [koterpillar/aloe#69]
Hello, this issue is a mix of a lot of things, but it seems to be directly related to the futures importing/aliasing done by aloe, so I'm making the issue here so perhaps it can be avoided.

The problem is that when I import aloe before making a PhantomJS webdriver instance, it fails deep inside the python networking code. See the following:

```
(virtualenv)[root@test1 www]# python
Python 2.7.2 (default, May  2 2012, 10:36:30) 
[GCC 4.4.6 20110731 (Red Hat 4.4.6-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from selenium import webdriver
>>> webdriver.PhantomJS()
<selenium.webdriver.phantomjs.webdriver.WebDriver (session="80570a80-775d-11e5-88ad-3d7c79b21aa6")>
>>>
```

vs

```
(virtualenv)[root@test1 www]# python
Python 2.7.2 (default, May  2 2012, 10:36:30) 
[GCC 4.4.6 20110731 (Red Hat 4.4.6-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import aloe
>>> from selenium import webdriver
>>> webdriver.PhantomJS()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/smartfile/virtualenv/lib/python2.7/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 56, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/smartfile/virtualenv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 87, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/smartfile/virtualenv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 141, in start_session
    'desiredCapabilities': desired_capabilities,
  File "/usr/local/smartfile/virtualenv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 199, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/smartfile/virtualenv/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 395, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/smartfile/virtualenv/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 463, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "/usr/local/smartfile/virtualenv/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/local/smartfile/virtualenv/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/local/smartfile/virtualenv/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/smartfile/virtualenv/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1312, in http_open
    return self.do_open(http_client.HTTPConnection, req)
  File "/usr/local/smartfile/virtualenv/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/smartfile/virtualenv/lib/python2.7/site-packages/future/backports/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/smartfile/virtualenv/lib/python2.7/site-packages/future/backports/http/client.py", line 1121, in _send_request
    self.endheaders(body)
  File "/usr/local/smartfile/virtualenv/lib/python2.7/site-packages/future/backports/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/usr/local/smartfile/virtualenv/lib/python2.7/site-packages/future/backports/http/client.py", line 924, in _send_output
    self.send(msg)
  File "/usr/local/smartfile/virtualenv/lib/python2.7/site-packages/future/backports/http/client.py", line 860, in send
    self.connect()
  File "/usr/local/smartfile/virtualenv/lib/python2.7/site-packages/future/backports/http/client.py", line 838, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.error: Int or String expected
>>> 
```

I get the exact same error if I manually install the futures libraries with `from future import standard_library; standard_library.install_aliases()`

Would there be a way to mitigate this issue without just forking PhantomJS and trying to fix it? Maybe if the future aliases could be not installed conditionally inside aloe or something along those lines.

Thanks!

**Comment by koterpillar** [comment]
What are the versions of selenium, aloe, phantomjs and future? I have just tried on:
Python 2.7.10
aloe 0.0.31
selenium 2.48.0
phantomjs 2.0.0
and it works as expected:

```
Python 2.7.10 (default, Sep  7 2015, 13:51:49) 
[GCC 5.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import aloe
>>> from selenium import webdriver
>>> webdriver.PhantomJS()
<selenium.webdriver.phantomjs.webdriver.WebDriver (session="016c02d0-776b-11e5-bc6b-811ad24e3c8f")>
>>> 
```

**Comment by hylyh** [comment]
Thanks for your quick reply. Looks like I'm behind on phantomjs (at 1.9.8). I'm betting that is the issue, I'll get back you once I get it installed

**Comment by koterpillar** [comment]
I don't think phantomjs version is critical here, as the error is in Python land. I've included it for completeness. Can you please show the other versions still?

**Comment by hylyh** [comment]
Ah yeah that makes sense. The only other version difference I have from you is I'm on Python 2.7.2. My future version is 0.15.2

**Comment by hylyh** [comment]
Looks like the Python version is at fault here, it works for me as well on a machine with 2.7.10 and the same versions otherwise.

**Comment by koterpillar** [comment]
If this is still a problem for you, I suggest you take it up with Python Future. Aloe is written using Python 3 idioms, and future imports are necessary for the code to work on Python 2, so conditionally installing the aliases is not an option. (They are no-ops if you already run Python 3, if that helps.)

**Comment by hylyh** [comment]
Alright, thanks for the help!
